package com.przemas230.dietaapp.logic

/**
 * FR-66 (auto-calculating custom-recipe macros): generated from index.html's
 * INGREDIENT_MACRO_DB by scripts (not hand-transcribed) -- same reasoning as
 * SnackNutritionDb (FR-33/34): zero risk of transcription drift across
 * 105 entries. Regenerate by re-running the extraction script
 * against a newer index.html rather than hand-editing this file.
 */
data class IngredientMacroEntry(
    val per1Szt: Boolean,
    val kcal: Double,
    val protein: Double,
    val carbs: Double,
    val fat: Double,
    // null when per1Szt -- mirrors index.html's entries, which never set typicalG for per:"1szt" rows.
    val typicalG: Double?,
)

object IngredientMacroDb {
    val TABLE: Map<String, IngredientMacroEntry> = mapOf(
        "jajka" to IngredientMacroEntry(per1Szt = true, kcal = 78.0, protein = 6.3, carbs = 0.6, fat = 5.3, typicalG = null),
        "kurczak (pierś)" to IngredientMacroEntry(per1Szt = false, kcal = 165.0, protein = 31.0, carbs = 0.0, fat = 3.6, typicalG = 150.0),
        "indyk" to IngredientMacroEntry(per1Szt = false, kcal = 135.0, protein = 29.0, carbs = 0.0, fat = 1.6, typicalG = 150.0),
        "wołowina" to IngredientMacroEntry(per1Szt = false, kcal = 215.0, protein = 26.0, carbs = 0.0, fat = 12.0, typicalG = 150.0),
        "wieprzowina" to IngredientMacroEntry(per1Szt = false, kcal = 242.0, protein = 27.0, carbs = 0.0, fat = 14.0, typicalG = 150.0),
        "łosoś" to IngredientMacroEntry(per1Szt = false, kcal = 208.0, protein = 20.0, carbs = 0.0, fat = 13.0, typicalG = 150.0),
        "dorsz" to IngredientMacroEntry(per1Szt = false, kcal = 82.0, protein = 18.0, carbs = 0.0, fat = 0.7, typicalG = 150.0),
        "makrela" to IngredientMacroEntry(per1Szt = false, kcal = 205.0, protein = 19.0, carbs = 0.0, fat = 14.0, typicalG = 120.0),
        "pstrąg" to IngredientMacroEntry(per1Szt = false, kcal = 148.0, protein = 20.0, carbs = 0.0, fat = 7.0, typicalG = 150.0),
        "tuńczyk" to IngredientMacroEntry(per1Szt = false, kcal = 116.0, protein = 26.0, carbs = 0.0, fat = 1.0, typicalG = 100.0),
        "krewetki" to IngredientMacroEntry(per1Szt = false, kcal = 99.0, protein = 24.0, carbs = 0.2, fat = 0.3, typicalG = 100.0),
        "tofu" to IngredientMacroEntry(per1Szt = false, kcal = 76.0, protein = 8.0, carbs = 1.9, fat = 4.8, typicalG = 100.0),
        "ciecierzyca" to IngredientMacroEntry(per1Szt = false, kcal = 164.0, protein = 8.9, carbs = 27.0, fat = 2.6, typicalG = 150.0),
        "fasola" to IngredientMacroEntry(per1Szt = false, kcal = 127.0, protein = 8.7, carbs = 23.0, fat = 0.5, typicalG = 150.0),
        "soczewica" to IngredientMacroEntry(per1Szt = false, kcal = 116.0, protein = 9.0, carbs = 20.0, fat = 0.4, typicalG = 150.0),
        "hummus" to IngredientMacroEntry(per1Szt = false, kcal = 166.0, protein = 8.0, carbs = 14.0, fat = 10.0, typicalG = 50.0),
        "ryż" to IngredientMacroEntry(per1Szt = false, kcal = 130.0, protein = 2.7, carbs = 28.0, fat = 0.3, typicalG = 150.0),
        "kasza gryczana" to IngredientMacroEntry(per1Szt = false, kcal = 92.0, protein = 3.4, carbs = 20.0, fat = 0.6, typicalG = 150.0),
        "kasza jaglana" to IngredientMacroEntry(per1Szt = false, kcal = 118.0, protein = 3.5, carbs = 24.0, fat = 1.0, typicalG = 150.0),
        "kasza pęczak" to IngredientMacroEntry(per1Szt = false, kcal = 123.0, protein = 4.7, carbs = 26.0, fat = 0.4, typicalG = 150.0),
        "kasza bulgur" to IngredientMacroEntry(per1Szt = false, kcal = 83.0, protein = 3.0, carbs = 18.0, fat = 0.2, typicalG = 150.0),
        "kasza kuskus" to IngredientMacroEntry(per1Szt = false, kcal = 112.0, protein = 3.8, carbs = 23.0, fat = 0.2, typicalG = 150.0),
        "komosa ryżowa" to IngredientMacroEntry(per1Szt = false, kcal = 120.0, protein = 4.4, carbs = 21.0, fat = 1.9, typicalG = 150.0),
        "makaron soba" to IngredientMacroEntry(per1Szt = false, kcal = 99.0, protein = 5.0, carbs = 21.0, fat = 0.1, typicalG = 150.0),
        "makaron pszenny" to IngredientMacroEntry(per1Szt = false, kcal = 158.0, protein = 5.8, carbs = 31.0, fat = 0.9, typicalG = 150.0),
        "płatki owsiane" to IngredientMacroEntry(per1Szt = false, kcal = 379.0, protein = 13.0, carbs = 67.0, fat = 7.0, typicalG = 50.0),
        "mąka" to IngredientMacroEntry(per1Szt = false, kcal = 364.0, protein = 10.0, carbs = 76.0, fat = 1.0, typicalG = 60.0),
        "chleb żytni" to IngredientMacroEntry(per1Szt = true, kcal = 80.0, protein = 2.5, carbs = 15.0, fat = 1.0, typicalG = null),
        "chleb pszenny" to IngredientMacroEntry(per1Szt = true, kcal = 90.0, protein = 3.0, carbs = 17.0, fat = 1.0, typicalG = null),
        "bułka pszenna" to IngredientMacroEntry(per1Szt = true, kcal = 150.0, protein = 5.0, carbs = 29.0, fat = 1.5, typicalG = null),
        "wafle chrupkie" to IngredientMacroEntry(per1Szt = true, kcal = 35.0, protein = 1.0, carbs = 7.0, fat = 0.3, typicalG = null),
        "tortilla" to IngredientMacroEntry(per1Szt = true, kcal = 140.0, protein = 4.0, carbs = 24.0, fat = 3.5, typicalG = null),
        "ziemniaki" to IngredientMacroEntry(per1Szt = false, kcal = 77.0, protein = 2.0, carbs = 17.0, fat = 0.1, typicalG = 200.0),
        "batat" to IngredientMacroEntry(per1Szt = false, kcal = 86.0, protein = 1.6, carbs = 20.0, fat = 0.1, typicalG = 200.0),
        "cebula" to IngredientMacroEntry(per1Szt = false, kcal = 40.0, protein = 1.1, carbs = 9.3, fat = 0.1, typicalG = 70.0),
        "czerwona cebula" to IngredientMacroEntry(per1Szt = false, kcal = 40.0, protein = 1.1, carbs = 9.3, fat = 0.1, typicalG = 70.0),
        "cukinia" to IngredientMacroEntry(per1Szt = false, kcal = 17.0, protein = 1.2, carbs = 3.1, fat = 0.3, typicalG = 200.0),
        "marchewka" to IngredientMacroEntry(per1Szt = true, kcal = 25.0, protein = 0.5, carbs = 5.6, fat = 0.1, typicalG = null),
        "burak" to IngredientMacroEntry(per1Szt = false, kcal = 43.0, protein = 1.6, carbs = 10.0, fat = 0.2, typicalG = 100.0),
        "ogórek" to IngredientMacroEntry(per1Szt = true, kcal = 20.0, protein = 0.6, carbs = 3.0, fat = 0.1, typicalG = null),
        "ogórek kiszony" to IngredientMacroEntry(per1Szt = false, kcal = 12.0, protein = 0.7, carbs = 1.9, fat = 0.2, typicalG = 60.0),
        "papryka" to IngredientMacroEntry(per1Szt = true, kcal = 31.0, protein = 1.0, carbs = 6.0, fat = 0.3, typicalG = null),
        "papryka słodka (mielona)" to IngredientMacroEntry(per1Szt = false, kcal = 282.0, protein = 14.0, carbs = 34.0, fat = 13.0, typicalG = 2.0),
        "pomidor" to IngredientMacroEntry(per1Szt = true, kcal = 22.0, protein = 1.0, carbs = 4.0, fat = 0.2, typicalG = null),
        "pomidorki koktajlowe" to IngredientMacroEntry(per1Szt = false, kcal = 18.0, protein = 0.9, carbs = 3.9, fat = 0.2, typicalG = 100.0),
        "koncentrat / passata pomidorowa" to IngredientMacroEntry(per1Szt = false, kcal = 82.0, protein = 4.3, carbs = 19.0, fat = 0.5, typicalG = 100.0),
        "rzodkiewka" to IngredientMacroEntry(per1Szt = false, kcal = 16.0, protein = 0.7, carbs = 3.4, fat = 0.1, typicalG = 60.0),
        "szpinak" to IngredientMacroEntry(per1Szt = false, kcal = 23.0, protein = 2.9, carbs = 3.6, fat = 0.4, typicalG = 60.0),
        "jarmuż" to IngredientMacroEntry(per1Szt = false, kcal = 49.0, protein = 4.3, carbs = 8.8, fat = 0.9, typicalG = 60.0),
        "sałata / mix sałat" to IngredientMacroEntry(per1Szt = false, kcal = 15.0, protein = 1.4, carbs = 2.9, fat = 0.2, typicalG = 50.0),
        "brokuł" to IngredientMacroEntry(per1Szt = false, kcal = 34.0, protein = 2.8, carbs = 6.6, fat = 0.4, typicalG = 150.0),
        "kalafior" to IngredientMacroEntry(per1Szt = false, kcal = 25.0, protein = 1.9, carbs = 5.0, fat = 0.3, typicalG = 150.0),
        "seler naciowy" to IngredientMacroEntry(per1Szt = false, kcal = 16.0, protein = 0.7, carbs = 3.0, fat = 0.2, typicalG = 50.0),
        "czosnek" to IngredientMacroEntry(per1Szt = false, kcal = 149.0, protein = 6.4, carbs = 33.0, fat = 0.5, typicalG = 3.0),
        "koperek" to IngredientMacroEntry(per1Szt = false, kcal = 43.0, protein = 3.5, carbs = 7.0, fat = 1.1, typicalG = 5.0),
        "szczypiorek" to IngredientMacroEntry(per1Szt = false, kcal = 30.0, protein = 3.3, carbs = 4.4, fat = 0.7, typicalG = 5.0),
        "kiełki" to IngredientMacroEntry(per1Szt = false, kcal = 30.0, protein = 3.0, carbs = 4.0, fat = 0.5, typicalG = 20.0),
        "mrożone warzywa" to IngredientMacroEntry(per1Szt = false, kcal = 60.0, protein = 3.0, carbs = 10.0, fat = 0.5, typicalG = 150.0),
        "pieczarki" to IngredientMacroEntry(per1Szt = false, kcal = 22.0, protein = 3.1, carbs = 3.3, fat = 0.3, typicalG = 100.0),
        "dynia" to IngredientMacroEntry(per1Szt = false, kcal = 26.0, protein = 1.0, carbs = 6.5, fat = 0.1, typicalG = 150.0),
        "fasolka szparagowa" to IngredientMacroEntry(per1Szt = false, kcal = 31.0, protein = 1.8, carbs = 7.0, fat = 0.2, typicalG = 120.0),
        "groszek zielony" to IngredientMacroEntry(per1Szt = false, kcal = 81.0, protein = 5.4, carbs = 14.0, fat = 0.4, typicalG = 80.0),
        "awokado" to IngredientMacroEntry(per1Szt = false, kcal = 160.0, protein = 2.0, carbs = 8.5, fat = 14.7, typicalG = 100.0),
        "banan" to IngredientMacroEntry(per1Szt = true, kcal = 105.0, protein = 1.3, carbs = 27.0, fat = 0.4, typicalG = null),
        "jabłko" to IngredientMacroEntry(per1Szt = true, kcal = 78.0, protein = 0.4, carbs = 21.0, fat = 0.3, typicalG = null),
        "gruszka" to IngredientMacroEntry(per1Szt = true, kcal = 86.0, protein = 0.6, carbs = 23.0, fat = 0.2, typicalG = null),
        "cytryna" to IngredientMacroEntry(per1Szt = true, kcal = 17.0, protein = 0.6, carbs = 5.0, fat = 0.2, typicalG = null),
        "kiwi" to IngredientMacroEntry(per1Szt = true, kcal = 42.0, protein = 0.8, carbs = 10.0, fat = 0.4, typicalG = null),
        "pomarańcza" to IngredientMacroEntry(per1Szt = true, kcal = 62.0, protein = 1.2, carbs = 15.0, fat = 0.2, typicalG = null),
        "maliny" to IngredientMacroEntry(per1Szt = false, kcal = 32.0, protein = 1.2, carbs = 5.4, fat = 0.5, typicalG = 125.0),
        "borówki / jagody" to IngredientMacroEntry(per1Szt = false, kcal = 43.0, protein = 0.7, carbs = 9.7, fat = 0.5, typicalG = 125.0),
        "truskawki" to IngredientMacroEntry(per1Szt = false, kcal = 32.0, protein = 0.7, carbs = 7.7, fat = 0.3, typicalG = 150.0),
        "ananas" to IngredientMacroEntry(per1Szt = false, kcal = 50.0, protein = 0.5, carbs = 13.0, fat = 0.1, typicalG = 100.0),
        "migdały" to IngredientMacroEntry(per1Szt = false, kcal = 579.0, protein = 21.0, carbs = 22.0, fat = 50.0, typicalG = 20.0),
        "orzechy" to IngredientMacroEntry(per1Szt = false, kcal = 654.0, protein = 15.0, carbs = 14.0, fat = 65.0, typicalG = 20.0),
        "pestki (dyni/słonecznika)" to IngredientMacroEntry(per1Szt = false, kcal = 559.0, protein = 30.0, carbs = 11.0, fat = 49.0, typicalG = 15.0),
        "siemię lniane / chia" to IngredientMacroEntry(per1Szt = false, kcal = 486.0, protein = 17.0, carbs = 42.0, fat = 31.0, typicalG = 10.0),
        "sezam" to IngredientMacroEntry(per1Szt = false, kcal = 573.0, protein = 18.0, carbs = 23.0, fat = 50.0, typicalG = 10.0),
        "masło orzechowe / migdałowe" to IngredientMacroEntry(per1Szt = false, kcal = 588.0, protein = 25.0, carbs = 20.0, fat = 50.0, typicalG = 15.0),
        "oliwa z oliwek" to IngredientMacroEntry(per1Szt = true, kcal = 40.0, protein = 0.0, carbs = 0.0, fat = 4.5, typicalG = null),
        "olej kokosowy" to IngredientMacroEntry(per1Szt = true, kcal = 40.0, protein = 0.0, carbs = 0.0, fat = 4.5, typicalG = null),
        "olej sezamowy" to IngredientMacroEntry(per1Szt = true, kcal = 40.0, protein = 0.0, carbs = 0.0, fat = 4.5, typicalG = null),
        "masło klarowane" to IngredientMacroEntry(per1Szt = true, kcal = 42.0, protein = 0.0, carbs = 0.0, fat = 4.7, typicalG = null),
        "oliwki" to IngredientMacroEntry(per1Szt = false, kcal = 115.0, protein = 0.8, carbs = 6.0, fat = 11.0, typicalG = 20.0),
        "miód" to IngredientMacroEntry(per1Szt = true, kcal = 21.0, protein = 0.0, carbs = 5.7, fat = 0.0, typicalG = null),
        "dżem" to IngredientMacroEntry(per1Szt = false, kcal = 250.0, protein = 0.4, carbs = 61.0, fat = 0.1, typicalG = 20.0),
        "gorzka czekolada" to IngredientMacroEntry(per1Szt = false, kcal = 546.0, protein = 5.0, carbs = 46.0, fat = 31.0, typicalG = 15.0),
        "granola" to IngredientMacroEntry(per1Szt = false, kcal = 450.0, protein = 10.0, carbs = 60.0, fat = 18.0, typicalG = 40.0),
        "daktyle suszone" to IngredientMacroEntry(per1Szt = false, kcal = 282.0, protein = 2.5, carbs = 75.0, fat = 0.4, typicalG = 20.0),
        "rodzynki / żurawina" to IngredientMacroEntry(per1Szt = false, kcal = 299.0, protein = 3.0, carbs = 79.0, fat = 0.5, typicalG = 15.0),
        "morele suszone" to IngredientMacroEntry(per1Szt = false, kcal = 241.0, protein = 3.4, carbs = 63.0, fat = 0.5, typicalG = 20.0),
        "napój roślinny (migdałowy/owsiany/kokosowy)" to IngredientMacroEntry(per1Szt = false, kcal = 40.0, protein = 0.5, carbs = 6.0, fat = 1.5, typicalG = 200.0),
        "mleko kokosowe" to IngredientMacroEntry(per1Szt = false, kcal = 180.0, protein = 1.8, carbs = 3.0, fat = 18.0, typicalG = 100.0),
        "wiórki kokosowe" to IngredientMacroEntry(per1Szt = false, kcal = 660.0, protein = 6.9, carbs = 24.0, fat = 65.0, typicalG = 10.0),
        "jogurt bez laktozy" to IngredientMacroEntry(per1Szt = false, kcal = 61.0, protein = 3.5, carbs = 4.7, fat = 3.3, typicalG = 150.0),
        "skyr bez laktozy" to IngredientMacroEntry(per1Szt = false, kcal = 63.0, protein = 11.0, carbs = 4.0, fat = 0.2, typicalG = 150.0),
        "serek bez laktozy" to IngredientMacroEntry(per1Szt = false, kcal = 98.0, protein = 11.0, carbs = 3.4, fat = 4.3, typicalG = 150.0),
        "twaróg bez laktozy" to IngredientMacroEntry(per1Szt = false, kcal = 98.0, protein = 18.0, carbs = 3.5, fat = 1.5, typicalG = 150.0),
        "feta / ser bez laktozy" to IngredientMacroEntry(per1Szt = false, kcal = 264.0, protein = 14.0, carbs = 4.0, fat = 21.0, typicalG = 50.0),
        "odżywka białkowa" to IngredientMacroEntry(per1Szt = true, kcal = 120.0, protein = 24.0, carbs = 3.0, fat = 1.5, typicalG = null),
        "sos sojowy / tamari" to IngredientMacroEntry(per1Szt = false, kcal = 60.0, protein = 8.0, carbs = 6.0, fat = 0.0, typicalG = 15.0),
        "ocet balsamiczny" to IngredientMacroEntry(per1Szt = false, kcal = 88.0, protein = 0.5, carbs = 17.0, fat = 0.0, typicalG = 15.0),
        "bulion warzywny" to IngredientMacroEntry(per1Szt = false, kcal = 6.0, protein = 0.3, carbs = 0.8, fat = 0.2, typicalG = 250.0),
        "musztarda" to IngredientMacroEntry(per1Szt = false, kcal = 66.0, protein = 4.0, carbs = 5.0, fat = 3.3, typicalG = 10.0),
        "pasta curry" to IngredientMacroEntry(per1Szt = false, kcal = 120.0, protein = 2.0, carbs = 10.0, fat = 8.0, typicalG = 15.0),
    )
}
