package com.przemas230.dietaapp.logic

/**
 * FR-25: Polish genitive (dopełniacz) form per canonical ingredient, needed
 * after any quantity+unit ("10 g migdałów", "4 łyżki płatków owsianych") on
 * the shopping list -- unlike pantry tile titles (FR-29) or recipe cards,
 * which lead with the plain nominative name. Data copied verbatim from
 * index.html's CANON_GENITIVE, not retyped by hand, to avoid transcription
 * drift across ~155 entries.
 */
object ShoppingDisplay {
    private val CANON_GENITIVE: Map<String, String> = mapOf(
        "jogurt bez laktozy" to "jogurtu bez laktozy",
        "skyr bez laktozy" to "skyru bez laktozy",
        "serek bez laktozy" to "serka bez laktozy",
        "twaróg bez laktozy" to "twarogu bez laktozy",
        "feta / ser bez laktozy" to "fety / sera bez laktozy",
        "masło klarowane" to "masła klarowanego",
        "odżywka białkowa" to "odżywki białkowej",
        "cebula" to "cebuli",
        "czerwona cebula" to "czerwonej cebuli",
        "cukinia" to "cukinii",
        "marchewka" to "marchewki",
        "pietruszka (korzeń)" to "pietruszki (korzeń)",
        "burak" to "buraka",
        "ogórek" to "ogórka",
        "ogórek kiszony" to "ogórka kiszonego",
        "papryka" to "papryki",
        "pomidor" to "pomidora",
        "pomidorki koktajlowe" to "pomidorków koktajlowych",
        "rzodkiewka" to "rzodkiewki",
        "szpinak" to "szpinaku",
        "jarmuż" to "jarmużu",
        "sałata / mix sałat" to "sałaty / mix sałat",
        "brokuł" to "brokułu",
        "kalafior" to "kalafiora",
        "seler naciowy" to "selera naciowego",
        "czosnek" to "czosnku",
        "koperek" to "koperku",
        "szczypiorek" to "szczypiorku",
        "kiełki" to "kiełków",
        "mrożone warzywa" to "mrożonych warzyw",
        "ziemniaki" to "ziemniaków",
        "batat" to "batata",
        "awokado" to "awokado",
        "banan" to "banana",
        "jabłko" to "jabłka",
        "gruszka" to "gruszki",
        "cytryna" to "cytryny",
        "limonka" to "limonki",
        "kiwi" to "kiwi",
        "maliny" to "malin",
        "borówki / jagody" to "borówek / jagód",
        "truskawki" to "truskawek",
        "morele suszone" to "moreli suszonych",
        "ananas" to "ananasa",
        "imbir" to "imbiru",
        "rodzynki / żurawina" to "rodzynek / żurawiny",
        "jajka" to "jajek",
        "kurczak (pierś)" to "kurczaka (pierś)",
        "indyk" to "indyka",
        "wołowina" to "wołowiny",
        "wieprzowina" to "wieprzowiny",
        "dorsz" to "dorsza",
        "łosoś" to "łososia",
        "pstrąg" to "pstrąga",
        "makrela" to "makreli",
        "tuńczyk" to "tuńczyka",
        "krewetki" to "krewetek",
        "tofu" to "tofu",
        "ciecierzyca" to "ciecierzycy",
        "fasola" to "fasoli",
        "soczewica" to "soczewicy",
        "hummus" to "hummusu",
        "orzechy" to "orzechów",
        "migdały" to "migdałów",
        "pestki (dyni/słonecznika)" to "pestek (dyni/słonecznika)",
        "siemię lniane / chia" to "siemienia lnianego / chia",
        "sezam" to "sezamu",
        "masło orzechowe / migdałowe" to "masła orzechowego / migdałowego",
        "chleb żytni" to "chleba żytniego",
        "wafle chrupkie" to "wafli chrupkich",
        "tortilla" to "tortilli",
        "kasza gryczana" to "kaszy gryczanej",
        "kasza jaglana" to "kaszy jaglanej",
        "kasza pęczak" to "kaszy pęczak",
        "kasza bulgur" to "kaszy bulgur",
        "komosa ryżowa" to "komosy ryżowej",
        "ryż" to "ryżu",
        "makaron soba" to "makaronu soba",
        "płatki owsiane" to "płatków owsianych",
        "mąka" to "mąki",
        "granola" to "granoli",
        "cynamon" to "cynamonu",
        "chili" to "chili",
        "curry (przyprawa)" to "curry (przyprawa)",
        "kumin" to "kuminu",
        "kurkuma" to "kurkumy",
        "majeranek" to "majeranku",
        "musztarda" to "musztardy",
        "oregano" to "oregano",
        "tymianek" to "tymianku",
        "sól" to "soli",
        "pieprz" to "pieprzu",
        "koncentrat / passata pomidorowa" to "koncentratu / passaty pomidorowej",
        "pasta curry" to "pasty curry",
        "sos sojowy / tamari" to "sosu sojowego / tamari",
        "oliwa z oliwek" to "oliwy z oliwek",
        "oliwki" to "oliwek",
        "olej kokosowy" to "oleju kokosowego",
        "olej sezamowy" to "oleju sezamowego",
        "ocet balsamiczny" to "octu balsamicznego",
        "miód" to "miodu",
        "zioła prowansalskie" to "ziół prowansalskich",
        "natka pietruszki" to "natki pietruszki",
        "bazylia" to "bazylii",
        "mięta" to "mięty",
        "papryka słodka (mielona)" to "papryki słodkiej (mielonej)",
        "wanilia" to "wanilii",
        "gałka muszkatołowa" to "gałki muszkatołowej",
        "sok z cytryny" to "soku z cytryny",
        "sok z limonki" to "soku z limonki",
        "napój roślinny (migdałowy/owsiany/kokosowy)" to "napoju roślinnego (migdałowego/owsianego/kokosowego)",
        "mleko kokosowe" to "mleka kokosowego",
        "wiórki kokosowe" to "wiórków kokosowych",
        "woda" to "wody",
        "bulion warzywny" to "bulionu warzywnego",
        "dynia" to "dyni",
        "fasolka szparagowa" to "fasolki szparagowej",
        "groszek zielony" to "groszku zielonego",
        "pieczarki" to "pieczarek",
        "owsiano-bananowa muffinka" to "owsiano-bananowej muffinki",
        "chleb pszenny" to "chleba pszennego",
        "płatki kukurydziane" to "płatków kukurydzianych",
        "dżem" to "dżemu",
        "bułka pszenna" to "bułki pszennej",
        "makaron pszenny" to "makaronu pszennego",
        "kasza kuskus" to "kaszy kuskus",
        "kakao" to "kakao",
        "daktyle suszone" to "daktyli suszonych",
        "gorzka czekolada" to "gorzkiej czekolady",
        "pomarańcza" to "pomarańczy",
        "arbuz" to "arbuza",
        "winogrona" to "winogron",
        "śliwki" to "śliwek",
        "brzoskwinia" to "brzoskwini",
        "grejpfrut" to "grejpfruta",
        "mandarynka" to "mandarynki",
        "czereśnie" to "czereśni",
        "wiśnie" to "wiśni",
        "ser żółty" to "sera żółtego",
        "maślanka" to "maślanki",
        "kefir" to "kefiru",
        "kawa" to "kawy",
        "kawa z mlekiem" to "kawy z mlekiem",
        "kawa z cukrem" to "kawy z cukrem",
        "kawa z mlekiem i cukrem" to "kawy z mlekiem i cukrem",
        "kawa z syropem" to "kawy z syropem",
        "kawa z mlekiem i syropem" to "kawy z mlekiem i syropem",
        "herbata" to "herbaty",
        "herbata z miodem" to "herbaty z miodem",
        "sok pomarańczowy" to "soku pomarańczowego",
        "sok jabłkowy" to "soku jabłkowego",
        "cola" to "coli",
        "piwo" to "piwa",
        "wino" to "wina",
        "prince polo" to "prince polo",
        "snickers" to "snickersa",
        "mars" to "marsa",
        "twix" to "twixa",
        "bounty" to "bounty",
        "kinder bueno" to "kinder bueno",
        "czekolada mleczna" to "czekolady mlecznej",
        "ciastka" to "ciastek",
        "wafelek" to "wafelka",
        "pączek" to "pączka",
        "drożdżówka" to "drożdżówki",
        "rogalik" to "rogalika",
        "lody" to "lodów",
        "chipsy" to "chipsów",
        "paluszki" to "paluszków",
        "popcorn" to "popcornu",
        "precel" to "precla",
        "kabanos" to "kabanosa",
        "parówka" to "parówki",
        "kanapka" to "kanapki",
        "tost" to "tostu",
        "orzechy włoskie" to "orzechów włoskich",
    )

    /**
     * "10 g migdałów", "3 jajka" -- port of index.html's shopDisplayName.
     * Count-based items use the plural-agreement form (FR-29's
     * PantryDisplay), everything else uses the genitive table above,
     * falling back to the bare canonical name if it isn't in the table yet.
     */
    fun displayName(canonName: String, unitCat: String, qty: Double): String {
        if (unitCat == "count") return PantryDisplay.displayName(canonName, Math.round(qty).toInt())
        return CANON_GENITIVE[canonName] ?: canonName
    }

    private fun round(value: Double, decimals: Int): Double {
        val factor = Math.pow(10.0, decimals.toDouble())
        return Math.round(value * factor) / factor
    }

    private fun formatNum(value: Double): String =
        if (value == value.toLong().toDouble()) value.toLong().toString() else value.toString()

    /** "500 g" / "1.5 kg" / "3" -- port of index.html's formatQty, scoped to the weight/volume/count categories RecipePantryMatching actually produces. */
    fun formatQty(unitCat: String, qty: Double): String = when (unitCat) {
        "weight" -> if (qty >= 1000) "${formatNum(round(qty / 1000, 2))} kg" else "${formatNum(round(qty, 0))} g"
        "volume" -> if (qty >= 1000) "${formatNum(round(qty / 1000, 2))} l" else "${formatNum(round(qty, 0))} ml"
        else -> formatNum(round(qty, 2))
    }
}
