package com.przemas230.dietaapp.logic

/** kcal-per-unit lookup entry for FR-34's auto-fill -- per is "1szt" (per whole piece) or "100g" (needs typicalG when the typed text gave no explicit weight/volume). */
data class SnackNutrition(val per: String, val kcal: Int, val typicalG: Int?)

data class SnackKcalEstimate(val kcal: Int, val canonName: String, val basis: String)

/**
 * FR-33/34: quick-snack kcal lookup, keyed by the same canonical names the
 * pantry/recipe system already resolves ingredient text to
 * (RecipePantryMatching.parseIngredient's canonName, itself
 * IngredientCanon.pantryCanon(IngredientCanon.coreName(text))) -- port of
 * index.html's SNACK_NUTRITION_DB/estimateSnackKcal. Generated from the same
 * source data via a script, not retyped by hand across 336 entries, to
 * avoid transcription drift -- see android/PARITY.md and IngredientCanon.kt
 * for the same approach used there.
 */
object SnackNutritionDb {
    val TABLE: Map<String, SnackNutrition> = mapOf(
        "banan" to SnackNutrition("1szt", 105, null),
        "jabłko" to SnackNutrition("1szt", 78, null),
        "gruszka" to SnackNutrition("1szt", 86, null),
        "kiwi" to SnackNutrition("1szt", 42, null),
        "cytryna" to SnackNutrition("1szt", 17, null),
        "jajka" to SnackNutrition("1szt", 78, null),
        "chleb żytni" to SnackNutrition("1szt", 80, null),
        "chleb pszenny" to SnackNutrition("1szt", 90, null),
        "bułka pszenna" to SnackNutrition("1szt", 150, null),
        "marchewka" to SnackNutrition("1szt", 25, null),
        "ogórek" to SnackNutrition("1szt", 20, null),
        "pomidor" to SnackNutrition("1szt", 22, null),
        "papryka" to SnackNutrition("1szt", 31, null),
        "truskawki" to SnackNutrition("100g", 32, 150),
        "maliny" to SnackNutrition("100g", 52, 125),
        "borówki / jagody" to SnackNutrition("100g", 57, 125),
        "ananas" to SnackNutrition("100g", 50, 150),
        "awokado" to SnackNutrition("100g", 160, 100),
        "jogurt bez laktozy" to SnackNutrition("100g", 61, 150),
        "skyr bez laktozy" to SnackNutrition("100g", 63, 150),
        "twaróg bez laktozy" to SnackNutrition("100g", 98, 100),
        "serek bez laktozy" to SnackNutrition("100g", 150, 100),
        "mleko kokosowe" to SnackNutrition("100g", 50, 100),
        "kurczak (pierś)" to SnackNutrition("100g", 110, 150),
        "indyk" to SnackNutrition("100g", 110, 150),
        "tuńczyk" to SnackNutrition("100g", 116, 100),
        "łosoś" to SnackNutrition("100g", 208, 120),
        "dorsz" to SnackNutrition("100g", 82, 150),
        "płatki owsiane" to SnackNutrition("100g", 380, 40),
        "ryż" to SnackNutrition("100g", 130, 150),
        "kasza gryczana" to SnackNutrition("100g", 92, 150),
        "kasza jaglana" to SnackNutrition("100g", 97, 150),
        "orzechy" to SnackNutrition("100g", 650, 30),
        "migdały" to SnackNutrition("100g", 579, 30),
        "pestki (dyni/słonecznika)" to SnackNutrition("100g", 550, 20),
        "miód" to SnackNutrition("100g", 304, 20),
        "dżem" to SnackNutrition("100g", 250, 20),
        "gorzka czekolada" to SnackNutrition("100g", 550, 20),
        "daktyle suszone" to SnackNutrition("100g", 277, 40),
        "granola" to SnackNutrition("100g", 450, 40),
        "hummus" to SnackNutrition("100g", 166, 60),
        "ciecierzyca" to SnackNutrition("100g", 164, 100),
        "ziemniaki" to SnackNutrition("100g", 87, 150),
        "batat" to SnackNutrition("100g", 86, 150),
        "arbuz" to SnackNutrition("100g", 30, 200),
        "winogrona" to SnackNutrition("100g", 69, 100),
        "śliwki" to SnackNutrition("1szt", 30, null),
        "brzoskwinia" to SnackNutrition("1szt", 59, null),
        "grejpfrut" to SnackNutrition("1szt", 97, null),
        "mandarynka" to SnackNutrition("1szt", 40, null),
        "czereśnie" to SnackNutrition("100g", 63, 100),
        "wiśnie" to SnackNutrition("100g", 52, 100),
        "rzodkiewka" to SnackNutrition("100g", 16, 100),
        "seler naciowy" to SnackNutrition("1szt", 6, null),
        "brokuł" to SnackNutrition("100g", 34, 100),
        "ser żółty" to SnackNutrition("100g", 350, 30),
        "maślanka" to SnackNutrition("100g", 40, 250),
        "kefir" to SnackNutrition("100g", 55, 250),
        "kawa" to SnackNutrition("1szt", 2, null),
        "kawa z mlekiem" to SnackNutrition("1szt", 40, null),
        "kawa z cukrem" to SnackNutrition("1szt", 20, null),
        "kawa z mlekiem i cukrem" to SnackNutrition("1szt", 55, null),
        "kawa z syropem" to SnackNutrition("1szt", 150, null),
        "kawa z mlekiem i syropem" to SnackNutrition("1szt", 170, null),
        "herbata" to SnackNutrition("1szt", 1, null),
        "herbata z miodem" to SnackNutrition("1szt", 40, null),
        "sok pomarańczowy" to SnackNutrition("100g", 45, 200),
        "sok jabłkowy" to SnackNutrition("100g", 46, 200),
        "cola" to SnackNutrition("100g", 42, 330),
        "piwo" to SnackNutrition("100g", 43, 500),
        "wino" to SnackNutrition("100g", 83, 150),
        "prince polo" to SnackNutrition("1szt", 180, null),
        "snickers" to SnackNutrition("1szt", 250, null),
        "mars" to SnackNutrition("1szt", 228, null),
        "twix" to SnackNutrition("1szt", 248, null),
        "bounty" to SnackNutrition("1szt", 276, null),
        "kinder bueno" to SnackNutrition("1szt", 232, null),
        "czekolada mleczna" to SnackNutrition("100g", 534, 25),
        "ciastka" to SnackNutrition("100g", 480, 30),
        "wafelek" to SnackNutrition("1szt", 130, null),
        "pączek" to SnackNutrition("1szt", 300, null),
        "drożdżówka" to SnackNutrition("1szt", 280, null),
        "rogalik" to SnackNutrition("1szt", 230, null),
        "lody" to SnackNutrition("1szt", 110, null),
        "chipsy" to SnackNutrition("100g", 536, 30),
        "paluszki" to SnackNutrition("100g", 380, 30),
        "popcorn" to SnackNutrition("100g", 400, 30),
        "precel" to SnackNutrition("1szt", 250, null),
        "kabanos" to SnackNutrition("1szt", 80, null),
        "parówka" to SnackNutrition("1szt", 130, null),
        "kanapka" to SnackNutrition("1szt", 250, null),
        "tost" to SnackNutrition("1szt", 200, null),
        "morela" to SnackNutrition("1szt", 17, null),
        "nektarynka" to SnackNutrition("1szt", 60, null),
        "figa" to SnackNutrition("1szt", 47, null),
        "figi" to SnackNutrition("100g", 249, 30),
        "kaki" to SnackNutrition("1szt", 118, null),
        "granat" to SnackNutrition("100g", 83, 150),
        "mango" to SnackNutrition("100g", 60, 200),
        "papaja" to SnackNutrition("100g", 43, 200),
        "liczi" to SnackNutrition("1szt", 6, null),
        "marakuja" to SnackNutrition("1szt", 17, null),
        "gujawa" to SnackNutrition("100g", 68, 100),
        "pomelo" to SnackNutrition("100g", 38, 200),
        "agrest" to SnackNutrition("100g", 44, 100),
        "porzeczki czerwone" to SnackNutrition("100g", 56, 100),
        "porzeczki czarne" to SnackNutrition("100g", 63, 100),
        "jeżyny" to SnackNutrition("100g", 43, 100),
        "żurawina" to SnackNutrition("100g", 46, 50),
        "melon" to SnackNutrition("100g", 34, 200),
        "rabarbar" to SnackNutrition("100g", 21, 100),
        "jabłko suszone" to SnackNutrition("100g", 244, 20),
        "gruszka suszona" to SnackNutrition("100g", 262, 20),
        "chipsy bananowe" to SnackNutrition("100g", 346, 20),
        "śliwki suszone" to SnackNutrition("100g", 240, 30),
        "rodzynki / żurawina" to SnackNutrition("100g", 299, 20),
        "owoc smoka" to SnackNutrition("100g", 60, 150),
        "karambola" to SnackNutrition("100g", 31, 100),
        "longan" to SnackNutrition("100g", 60, 100),
        "ananas suszony" to SnackNutrition("100g", 260, 20),
        "kokos" to SnackNutrition("100g", 354, 30),
        "wiórki kokosowe" to SnackNutrition("100g", 660, 15),
        "ogórek kiszony" to SnackNutrition("1szt", 7, null),
        "kapusta biała" to SnackNutrition("100g", 25, 100),
        "kapusta kiszona" to SnackNutrition("100g", 19, 100),
        "kapusta czerwona" to SnackNutrition("100g", 31, 100),
        "kalafior" to SnackNutrition("100g", 25, 100),
        "cukinia" to SnackNutrition("100g", 17, 100),
        "bakłażan" to SnackNutrition("100g", 25, 100),
        "por" to SnackNutrition("100g", 61, 50),
        "cebula" to SnackNutrition("100g", 40, 50),
        "czosnek" to SnackNutrition("1szt", 4, null),
        "pieczarki" to SnackNutrition("100g", 22, 100),
        "szpinak" to SnackNutrition("100g", 23, 80),
        "jarmuż" to SnackNutrition("100g", 49, 80),
        "kukurydza" to SnackNutrition("100g", 86, 100),
        "groszek zielony" to SnackNutrition("100g", 81, 100),
        "fasolka szparagowa" to SnackNutrition("100g", 31, 100),
        "dynia" to SnackNutrition("100g", 26, 150),
        "burak" to SnackNutrition("100g", 43, 100),
        "seler korzeniowy" to SnackNutrition("100g", 42, 100),
        "pietruszka korzeń" to SnackNutrition("100g", 43, 100),
        "szparagi" to SnackNutrition("100g", 20, 100),
        "chrzan" to SnackNutrition("100g", 48, 10),
        "oliwki" to SnackNutrition("100g", 115, 30),
        "kiszony ogórek małosolny" to SnackNutrition("1szt", 5, null),
        "kalarepa" to SnackNutrition("100g", 27, 100),
        "pomidory suszone" to SnackNutrition("100g", 258, 20),
        "papryczka chili" to SnackNutrition("1szt", 4, null),
        "imbir" to SnackNutrition("100g", 80, 10),
        "warzywa mieszane" to SnackNutrition("100g", 45, 200),
        "mleko półtłuste" to SnackNutrition("100g", 50, 250),
        "mleko pełnotłuste" to SnackNutrition("100g", 61, 250),
        "jogurt naturalny" to SnackNutrition("100g", 61, 150),
        "jogurt grecki" to SnackNutrition("100g", 97, 150),
        "jogurt owocowy" to SnackNutrition("100g", 95, 150),
        "serek wiejski" to SnackNutrition("100g", 98, 150),
        "ser mozzarella" to SnackNutrition("100g", 280, 30),
        "ser feta" to SnackNutrition("100g", 264, 30),
        "ser pleśniowy" to SnackNutrition("100g", 353, 20),
        "ser topiony" to SnackNutrition("100g", 280, 20),
        "ser parmezan" to SnackNutrition("100g", 431, 15),
        "śmietana do kawy" to SnackNutrition("100g", 195, 30),
        "śmietana kremówka" to SnackNutrition("100g", 292, 30),
        "masło" to SnackNutrition("100g", 717, 10),
        "margaryna" to SnackNutrition("100g", 600, 10),
        "mleko migdałowe" to SnackNutrition("100g", 17, 250),
        "mleko owsiane" to SnackNutrition("100g", 47, 250),
        "mleko sojowe" to SnackNutrition("100g", 33, 250),
        "ricotta" to SnackNutrition("100g", 174, 50),
        "twarożek" to SnackNutrition("100g", 98, 100),
        "jajko sadzone" to SnackNutrition("1szt", 90, null),
        "omlet" to SnackNutrition("1szt", 300, null),
        "jajecznica" to SnackNutrition("1szt", 220, null),
        "skyr" to SnackNutrition("100g", 63, 150),
        "wołowina" to SnackNutrition("100g", 250, 150),
        "wieprzowina" to SnackNutrition("100g", 242, 150),
        "schab" to SnackNutrition("100g", 143, 150),
        "boczek" to SnackNutrition("100g", 541, 30),
        "szynka" to SnackNutrition("100g", 120, 30),
        "kiełbasa" to SnackNutrition("100g", 300, 50),
        "salami" to SnackNutrition("100g", 380, 20),
        "bekon" to SnackNutrition("100g", 541, 20),
        "pasztet" to SnackNutrition("100g", 312, 30),
        "kurczak panierowany" to SnackNutrition("100g", 220, 150),
        "skrzydełka kurczaka" to SnackNutrition("1szt", 90, null),
        "kaczka" to SnackNutrition("100g", 337, 150),
        "makrela" to SnackNutrition("100g", 205, 100),
        "śledź" to SnackNutrition("100g", 158, 100),
        "pstrąg" to SnackNutrition("100g", 148, 150),
        "krewetki" to SnackNutrition("100g", 99, 100),
        "łosoś wędzony" to SnackNutrition("100g", 142, 50),
        "tuńczyk w oleju" to SnackNutrition("100g", 189, 80),
        "kabanosy drobiowe" to SnackNutrition("1szt", 65, null),
        "klopsiki" to SnackNutrition("1szt", 60, null),
        "kotlet schabowy" to SnackNutrition("1szt", 320, null),
        "kotlet z mięsa mielonego" to SnackNutrition("1szt", 250, null),
        "gołąbki" to SnackNutrition("1szt", 180, null),
        "pulpety" to SnackNutrition("1szt", 55, null),
        "bagietka" to SnackNutrition("1szt", 270, null),
        "kawałek bagietki" to SnackNutrition("1szt", 80, null),
        "chleb graham" to SnackNutrition("1szt", 90, null),
        "chleb razowy" to SnackNutrition("1szt", 85, null),
        "pumpernikiel" to SnackNutrition("1szt", 65, null),
        "ryż brązowy" to SnackNutrition("100g", 111, 150),
        "kasza pęczak" to SnackNutrition("100g", 123, 150),
        "kasza bulgur" to SnackNutrition("100g", 83, 150),
        "komosa ryżowa" to SnackNutrition("100g", 120, 150),
        "makaron" to SnackNutrition("100g", 158, 150),
        "makaron pełnoziarnisty" to SnackNutrition("100g", 124, 150),
        "płatki kukurydziane" to SnackNutrition("100g", 357, 30),
        "musli" to SnackNutrition("100g", 375, 40),
        "otręby" to SnackNutrition("100g", 216, 15),
        "kuskus" to SnackNutrition("100g", 112, 150),
        "chleb chrupki" to SnackNutrition("1szt", 25, null),
        "tortilla" to SnackNutrition("1szt", 140, null),
        "pita" to SnackNutrition("1szt", 165, null),
        "bułka grahamka" to SnackNutrition("1szt", 130, null),
        "rogal świętomarciński" to SnackNutrition("1szt", 450, null),
        "fasola" to SnackNutrition("100g", 127, 150),
        "soczewica" to SnackNutrition("100g", 116, 150),
        "groch" to SnackNutrition("100g", 118, 150),
        "orzechy nerkowca" to SnackNutrition("100g", 553, 30),
        "orzechy laskowe" to SnackNutrition("100g", 628, 30),
        "orzeszki ziemne" to SnackNutrition("100g", 567, 30),
        "pistacje" to SnackNutrition("100g", 560, 30),
        "masło orzechowe" to SnackNutrition("100g", 588, 20),
        "masło migdałowe" to SnackNutrition("100g", 614, 20),
        "siemię lniane / chia" to SnackNutrition("100g", 510, 15),
        "pestki dyni" to SnackNutrition("100g", 559, 20),
        "pestki słonecznika" to SnackNutrition("100g", 584, 20),
        "cappuccino" to SnackNutrition("1szt", 80, null),
        "latte" to SnackNutrition("1szt", 120, null),
        "espresso" to SnackNutrition("1szt", 3, null),
        "kawa mrożona" to SnackNutrition("1szt", 200, null),
        "herbata mrożona" to SnackNutrition("100g", 30, 330),
        "woda smakowa" to SnackNutrition("100g", 20, 500),
        "napój energetyczny" to SnackNutrition("100g", 45, 250),
        "izotonik" to SnackNutrition("100g", 24, 500),
        "kakao" to SnackNutrition("1szt", 150, null),
        "sok pomidorowy" to SnackNutrition("100g", 17, 200),
        "sok grejpfrutowy" to SnackNutrition("100g", 39, 200),
        "sok multiwitamina" to SnackNutrition("100g", 48, 200),
        "smoothie owocowe" to SnackNutrition("100g", 60, 250),
        "lemoniada" to SnackNutrition("100g", 40, 330),
        "baton corny" to SnackNutrition("1szt", 96, null),
        "baton musli" to SnackNutrition("1szt", 110, null),
        "kit kat" to SnackNutrition("1szt", 218, null),
        "toblerone" to SnackNutrition("1szt", 45, null),
        "m&ms" to SnackNutrition("1szt", 240, null),
        "żelki" to SnackNutrition("100g", 343, 50),
        "lizak" to SnackNutrition("1szt", 45, null),
        "guma do żucia" to SnackNutrition("1szt", 5, null),
        "ciasto" to SnackNutrition("1szt", 350, null),
        "sernik" to SnackNutrition("1szt", 400, null),
        "szarlotka" to SnackNutrition("1szt", 300, null),
        "tiramisu" to SnackNutrition("1szt", 350, null),
        "brownie" to SnackNutrition("1szt", 280, null),
        "muffinka" to SnackNutrition("1szt", 350, null),
        "eklerka" to SnackNutrition("1szt", 250, null),
        "beza" to SnackNutrition("1szt", 100, null),
        "lody w rożku" to SnackNutrition("1szt", 200, null),
        "lody na patyku" to SnackNutrition("1szt", 250, null),
        "galaretka" to SnackNutrition("100g", 70, 150),
        "budyń" to SnackNutrition("100g", 105, 150),
        "pudding ryżowy" to SnackNutrition("100g", 120, 150),
        "cukier" to SnackNutrition("1szt", 16, null),
        "landrynki" to SnackNutrition("100g", 394, 20),
        "ptasie mleczko" to SnackNutrition("1szt", 60, null),
        "rurka z kremem" to SnackNutrition("1szt", 220, null),
        "pierniczki" to SnackNutrition("100g", 380, 30),
        "makowiec" to SnackNutrition("1szt", 320, null),
        "keks" to SnackNutrition("1szt", 300, null),
        "bita śmietana" to SnackNutrition("100g", 257, 20),
        "nutella" to SnackNutrition("100g", 539, 20),
        "oreo" to SnackNutrition("1szt", 53, null),
        "digestive" to SnackNutrition("1szt", 71, null),
        "krakersy" to SnackNutrition("100g", 440, 30),
        "chrupki kukurydziane" to SnackNutrition("100g", 480, 30),
        "orzeszki oblane czekoladą" to SnackNutrition("100g", 480, 30),
        "nachos" to SnackNutrition("100g", 490, 50),
        "pizza" to SnackNutrition("1szt", 285, null),
        "frytki" to SnackNutrition("1szt", 365, null),
        "hot dog" to SnackNutrition("1szt", 290, null),
        "hamburger" to SnackNutrition("1szt", 350, null),
        "cheeseburger" to SnackNutrition("1szt", 420, null),
        "kebab" to SnackNutrition("1szt", 700, null),
        "zapiekanka" to SnackNutrition("1szt", 550, null),
        "burrito" to SnackNutrition("1szt", 450, null),
        "taco" to SnackNutrition("1szt", 170, null),
        "sushi" to SnackNutrition("1szt", 40, null),
        "pierogi" to SnackNutrition("1szt", 60, null),
        "pierogi ruskie" to SnackNutrition("1szt", 400, null),
        "naleśnik" to SnackNutrition("1szt", 200, null),
        "gofr" to SnackNutrition("1szt", 280, null),
        "tortilla wrap" to SnackNutrition("1szt", 280, null),
        "chipsy tortilla" to SnackNutrition("100g", 490, 30),
        "precelki solone" to SnackNutrition("100g", 380, 30),
        "chrupki serowe" to SnackNutrition("100g", 520, 30),
        "orzeszki solone" to SnackNutrition("100g", 590, 30),
        "rosół" to SnackNutrition("1szt", 120, null),
        "żurek" to SnackNutrition("1szt", 250, null),
        "bigos" to SnackNutrition("1szt", 350, null),
        "schabowy z ziemniakami" to SnackNutrition("1szt", 650, null),
        "kurczak curry" to SnackNutrition("1szt", 450, null),
        "makaron carbonara" to SnackNutrition("1szt", 600, null),
        "pad thai" to SnackNutrition("1szt", 500, null),
        "ramen" to SnackNutrition("1szt", 450, null),
        "pho" to SnackNutrition("1szt", 350, null),
        "sałatka cesar" to SnackNutrition("1szt", 350, null),
        "sałatka grecka" to SnackNutrition("1szt", 300, null),
        "lasagne" to SnackNutrition("1szt", 480, null),
        "risotto" to SnackNutrition("1szt", 400, null),
        "chili con carne" to SnackNutrition("1szt", 380, null),
        "gulasz" to SnackNutrition("1szt", 350, null),
        "placki ziemniaczane" to SnackNutrition("1szt", 220, null),
        "kopytka" to SnackNutrition("1szt", 320, null),
        "kluski śląskie" to SnackNutrition("1szt", 280, null),
        "leczo" to SnackNutrition("1szt", 250, null),
        "flaki" to SnackNutrition("1szt", 200, null),
        "zupa pomidorowa" to SnackNutrition("1szt", 150, null),
        "zupa ogórkowa" to SnackNutrition("1szt", 180, null),
        "zupa krem z brokułów" to SnackNutrition("1szt", 160, null),
        "zupa dyniowa" to SnackNutrition("1szt", 170, null),
        "barszcz czerwony" to SnackNutrition("1szt", 90, null),
        "kapuśniak" to SnackNutrition("1szt", 180, null),
        "pizza margherita" to SnackNutrition("1szt", 250, null),
        "spaghetti bolognese" to SnackNutrition("1szt", 550, null),
        "curry z ciecierzycą" to SnackNutrition("1szt", 380, null),
        "falafel" to SnackNutrition("1szt", 60, null),
        "gyros" to SnackNutrition("1szt", 600, null),
        "pad see ew" to SnackNutrition("1szt", 480, null),
        "katsu curry" to SnackNutrition("1szt", 550, null),
        "poke bowl" to SnackNutrition("1szt", 450, null),
        "bowl z quinoa" to SnackNutrition("1szt", 420, null),
        "sałata / mix sałat" to SnackNutrition("100g", 18, 50),
    )

    /**
     * "1 banan" -> 105 kcal, "150g ryżu" -> proportional, "jogurt" (no
     * explicit weight, "100g"-basis entry) -> entry.typicalG default
     * portion. Null when the text is blank or doesn't resolve to any
     * recognized canonical name -- callers must never show a row of zeros,
     * same rule as FR-64's Micronutrients.estimate.
     */
    fun estimate(text: String): SnackKcalEstimate? {
        val raw = text.trim()
        if (raw.isEmpty()) return null
        val parsed = RecipePantryMatching.parseIngredient(raw)
        val entry = TABLE[parsed.canonName] ?: return null
        return if (entry.per == "1szt") {
            val kcal = Math.round(entry.kcal * parsed.baseQty).toInt()
            SnackKcalEstimate(kcal, parsed.canonName, "${entry.kcal} kcal / 1 szt.")
        } else {
            val grams = if (parsed.unitCat == "weight" || parsed.unitCat == "volume") {
                parsed.baseQty
            } else {
                (entry.typicalG ?: 100) * parsed.baseQty
            }
            val kcal = Math.round(entry.kcal * grams / 100.0).toInt()
            SnackKcalEstimate(kcal, parsed.canonName, "${entry.kcal} kcal / 100 g × ${Math.round(grams)} g")
        }
    }
}
